use_default_settings:
  engines:
    keep_only:
      - google
      - brave
      - duckduckgo
      - startpage
      - bing

general:
  instance_name: "Private SearXNG"

search:
  formats:
    - html
    - json

engines:
  - name: google
    weight: 2.0
  - name: brave
    weight: 1.25
  - name: duckduckgo
    weight: 1.0
  - name: startpage
    weight: 1.0
  - name: bing
    disabled: false
    weight: 0.9

server:
  limiter: false
  image_proxy: false
  public_instance: false
